* Header                                                      :do:not:ignore:
#+TITLE: Goju-Ryu Karate
#+SUBTITLE: Cheat Sheet
#+MACRO: URL https://github.com/alhassy/GojuRyuCheatSheet
#+MACRO: ShowURL @@latex:{\tiny\hspace{6em}\url{ {{{URL}}} } }@@
# AUTHOR: [[http://www.cas.mcmaster.ca/~alhassm/][Musa Al-hassy]] {{{ShowURL}}}
#+AUTHOR: The McMaster Dojo {{{ShowURL}}}
#+EMAIL: alhassy@gmail.com
#+DESCRIPTION: This document is written by Musa Al-hassy for his learning in the Winter of 2019.
#+STARTUP: hideblocks
#+STARTUP: overview
#+TODO: spacing
#+OPTIONS: d:nil

#+INCLUDE: CheatSheet/CheatSheetSetup.org

* Dachi --Stance
#+begin_center
/Power is rooted in the feet, developed by the knees, and directed by the hips!/
#+end_center

| Heiko     dachi  | Natural stance             |
| Heisoku   dachi  | Attention stance           |
| Zenkutsu  dachi  | Forward stance             |
| Shiko     dachi  | Horse, Straddle stance     |
| Sanchin   dachi  | Hour Glass, Power   stance |
| Neko ashi dachi  | Cat stance                 |
| Tsuru ashi dachi | Stork stance               |
| Teiji dachi      | t-stance                   |
| Kokutsu dachi    | back stance                |
# | kiba dachi       | straddle stance            |
# | Musubu    dachi | Ready   stance         |
* spacing COMMENT newpage                                            :ignore:
  \newpage
* Uke --Block
#+begin_center
/90% of blocks are executed with the front hand, making it easier to counter!/
#+end_center

| Gedan bari   | Low sweeping block      |
| Jodan uke    | Rising block            |
| Chudan uke   | Inside forearm block    |
| Soto uke     | Outside forearm block   |
| Hariatoshi   | Low 3 point block       |
| Kakewaki uke | Cross block             |
| Mawashi uke  | Roundhouse block        |
| Kake uke     | Hook block              |
| Hiza uke     | Shin block              |
| Kakuto uke   | Crane head block        |
| Shuto uke    | Knife hand block        |
| Morto uke    | Augmented forearm block |
| Teisho uke   | Palm block              |

* spacing newpage                                            :ignore:
  \newpage
* Te --Hand Strikes
#+begin_center
#+latex: \vspace{-1em}
/The principles of expansion and contraction are a must when striking and as well for blocking!/
#+end_center

| Oi zuki      | Lunge punch       |
| Gy Aku zuki  | Reverse punch     |
| Kizama zuki  | Front jab         |
| Morto zuki   | Double fist punch |
| Rek Ken      | Backfist          |
| Ura Ken      | Back fist         |
| Tetsui       | Hammer fist       |
| Shuto        | Knifehand         |
| Teisho       | Palm heel         |
| Empi         | Elbow             |
| Mawashi zuki | Hook punch        |
| Nukite       | Finger strike     |

* Geri --Kick

#+begin_center
#+latex: \vspace{-1em}
/Except the instep roundhouse, remember to curl your toes for each and every kick!/
#+end_center

| Mae Geri Kekomi  | Front thrust kick      |
| Mae Geri Keage   | Front snap kick        |
| Yoko Geri Kekomi | Side thrust kick       |
| Yoko Geri Keage  | Side snap kick         |
| Kinsetsu Geri    | Joint kick, Knee break |
| Mawashi Geri     | Roundhouse kick        |
| Fumi Komi Geri   | Stomp kick             |
| Ushiro Geri      | Back kick              |
| Ashi Barai       | Foot sweep             |
| Mikasuki Geri    | Crescent kick          |
# | Hiza Geri        | Knee kick              |

#+begin_center
#+latex: \vspace{-0.3em}
/Remember the joint sequence: All kicks start with the hips, work to the knee, and finish with the ankle./
#+end_center
* Kata  --Forms                              
A /kata/ is the execution of a pre-defined series of movements which simulates
a confrontation against multiple opponents.
As such, remember to place yourself in the midst of your enemies and to visualise them
--this in turn necessitates rhythm and timing.
Moreover, full all-out intense kata will quickly demonstrate the importance of breathing.

\room
The key points of kata are:
| Pace | Breathing | Eyes | Focus | Kiai | Technique |

:Points_on_Kata:
There are six points which need to be incorporated into your katas.

Eyes - Look where you are headed before you move.

Pace - Learn the proper rhythm of the kata. This is usually set for the lower forms, but open to interpretation in the high forms.

Breathing - It is surprising the number of times you will need to be reminded to breathe. Inhaling and exhaling at the proper points is an important part of everything you do in karate.

Focus - Maintain your concentration on what it is that your are doing. Eventually, you should be able to perform a kata without actually 'thinking about it'.

Technique - Everything comes back to basics. Every stance, every strike, every kick - execute them to the best of your ability.

Kiai - Remember, you are simulating a fight against multiple attackers. Learn the proper kiai points in your katas and yell them out!
:End:

#+begin_center 
/Always concentrate on posture. Never rush through the kata./
/You will become what you practice./ 
/If you rush your movements without purpose, your kata will become ragged and weak./
#+end_center

\newpage
| *Kata --Forms* |
#
| Taikyoku Gedan       | First course lower          |
| Taikyoku Chudan      | First course middle         |
| Taikyoku Jodan       | First course upper          |
| Taikyoku Mawashi Uke | First course circular block |
| Taikyoku Kake Uke    | First course hooking block  |
| Gekisai Itch         | Attack & Smash 1            |
| Gakisai Ni           | Attack & Smash 2            |
| Sanchin              | Three Battles               |
| Tensho               | Rotating Palm               |
| Saifa                | Destroy & Defeat            |
| Seienchin            | Attack, Conquer, Suppress   |
| San Sei Ryu          | Thirty-six movements        |
| Shi Sho Chin         | Twenty-seven movements      |
| Seisan               | Fifty-six movements         |
| Seipai               | Eighteen movements          |

* Goju History

+ Sixth century Indian Buddhist monk Bodhidharma immigrated to China is credited with being the father of the martial arts.
+ Okinawa is a large island between Japan and China where many Chinese immigrated for trade.
+ As a major trading post, Okinawa produced a composite fighting style known as /Te/, “hand”, a forerunner of /karate/, “empty hand”.
+ In 1904, it was introduced into Okinawan public schools as part of the physical education curriculum.
+ In 1915, Okinawan Gichin Funakoshi brought the art to Japan, founding shotokan karate.
  - ‘Shoto’ is pine-waves and ‘kan’ is hall; shotokan was the name of his dojo.
+ Okinawan Miyagi Chojun popularised karate and incorporated Chinese forms to produce /goju ryu/, “hard soft style”.
  - He revised sanchin –the hard aspect of goju– and created tensho– the soft aspect.
  - These two kata are considered the essence of Goju Ryu.
  - The highest kata, Suparinpei, is said to contain the full syllabus of Goju Ryu.

  He designed goju's official insignia: The goju fist, which is half open and half closed preserving the
  dichotomy that goju ryu is neither completely hard nor completely soft.
  - The characters on the wrist read /go ju ryu/, while those on the banner read /kara te do/.
  - Its colours are white symbolising the purity of the beginner, black associated with the ideals of being
    a black belt, and red for mastery of the artform –the more red shaded in, the higher the rank of the bearer.

+ Miyagi's student Gogen ‘the cat’ Yamaguchi formed the All-Japan Karate-do Goju-kai, spreading the style throughout the world.

#+begin_center
/The ultimate aim of karate lies not in victory or defeat but in the perfection of character of its participants./
–Gichin Funakoshi
#+end_center

* spacing newpage                                            :ignore:
  \newpage

* Local Goju History
+ Don Warrener, 6ᵗʰ Dan :: Popularised Goju across southern Ontario.
  - Practising Goju since the age of 17; won the Canadian Karate Championships in 1968.
  - Studied under Richard Kim, Bob Dalgleish, Frank Lee, and 
     Goshi Yamaguchi --Gogen's son.

+ Philip McColl, 5ᵗʰ Dan :: Sensei of McMaster Dojo since 1984
    --the dojo was founded by Ray Greenway in 1969.
  - Began Karate at the age of 24 at the Delta club in Hamilton, run by Don Warrener.
  - Three of his graduated Shodans are World Champions 
     # World Karate Chamopnship in Argentina
  - Proficient in Goju Ryu, Kobudo --weaponry--, and Jujitsu.
  - Student Chris Stafford is the founder and Sensei of the [[http://torontokarate.ca/][Toronto Goju Ryu dojo]].

#+begin_center
/The ultimate aim of karate lies not in victory or defeat,/
/but in the perfection of character of its participants./
─Gichin Funakoshi
#+end_center

* General Terms

# latex:  {\vspace{-0em} .\hspace{20em} \fbox{Japanese numbers}} \\

#+begin_parallel 

| Sensei   | teacher           |
| O'Sensei | Teacher's teacher |
| Dojo     | training hall     |
| Nippon   | Japan             |
| Kihon    | Basics            |
| Gi       | Uniform           |
| Obi      | Belt              |
| Kyu      | Boy               |
| Dan      | Man               |
| Mukso    | Meditate          |
| Kimi     | Focus             |
| Kilskai  | Attention         |
| Rei      | Bow               |
| Ashimai  | Begin             |
| Yemai    | Stop              |
| Kia      | Yell              |

| [[https://www.linguajunkie.com/japanese/count-in-japanese-1-100][_Japanese Numbers_]] |

  |    0 | rei   |
  |    1 | ichi  |
  |    2 | ni    |
  |    3 | san   |
  |    4 | yon   |
  |    5 | go    |
  |    6 | roku  |
  |    7 | nana  |
  |    8 | hachi |
  |    9 | kyuu  |
  |   10 | juu   |
  |  100 | hyaku |
  | 1000 | sen   |
#+end_parallel

+ 11, 12, …, 19  are juu ichi, juu ni, …, juu kyuu.
+ 20, 30, …, 90  are ni juu, san juu, …, kyuu juu.
  - Likewise, 200, …, 900 are ni hyaku, …, kyuu hyaku.
    * Exceptions: 300 san byaku, 600 ro ppyaku, 800 ha ppyaku.
+ twenty-one, sixty-nine, eighty-two, … are 
   ni juu ichi, roku juu kyuu, hachi juu ni, … .
  - Likewise, 368 is three hundred and sixty-eight which is san byaku roku juu hachi.

** COMMENT Japanese Numbers
   |  0 | rei   |
   |  1 | ichi  |
   |  2 | ni    |
   |  3 | san   |
   |  4 | yon   |
   |  5 | go    |
   |  6 | roku  |
   |  7 | nana  |
   |  8 | hachi |
   |  9 | kyu   |
   | 10 | juu   |
         
* COMMENT Suggested Readings

Suggested reading list...

Traditional Goju Ryu KarateTraditional Goju Ryu Karate - by Don Warrener 
Traditional Goju is the very first book ever written in English demonstrating the kai shu or open hand katas of this beautiful flowing style of karate.


Advanced Traditional Goju Ryu KarateAdvanced Traditional Goju Ryu Karate - by Don Warrener
Features Kururumfa Kata and loads of philosophy and martial arts psychology for the advanced students only. This book will show you katsu or restoration techniques self defense and so much more never before taught in any book. If you are an advanced student this is a must have book which will teach many of the secrets of martial arts.

Tracy Warrener20th Century Samurai - by Don Warrener
Focuses on Richard 'Biggie' Kim's philosophy and psychology of the martial arts. It is the first book written on the history, philosophy and psychology of the Japanese martial arts by one of the most famous masters of the 20th Century.

The Classical ManThe Classical Man - by Richard Kim 
Sensei Richard Kim is the foremost authority on the facts, philosophies, psychology and morality of the ancient Samurai. With half a century of vast experience studying under renowned masters, Kim is extremely qualified to present The Classical Man.

Tracy WarrenerThe Weaponless Warriors - by Richard Kim 
An informal history of Okinawan karate and its growth, told through vignettes about its most famous practitioners, this rare chronicle is one of the most thoroughly researched histories on Okinawan karate, with rare photographs of the earliest pioneers of naha-te, the empty-hand style of self-defence.

Tracy WarrenerKarate Sensei - by Peter Urban 
There was only one Peter Urban. He was one of the most fortunate martial artists in America. He was trained by three of Japan's modern day masters: Mas Oyama, Gogen "The Cat" Yamaguichi and Richard Kim.

Tracy WarrenerKarate Dojo - by Peter Urban 
Karate is not only a means of self-defense; it is also a sport and a philosophy. The Karate Dojo: Traditions and Tales of a Martial Art examines each of these aspects through the colorful legends, tales, and traditions that are associated with the art.

Tracy WarrenerKarate Do My Way of Life - by Gichin Funakoshi 
Linking the time when karate was strictly an Okinawan art of self-defense shrouded in the deepest secrecy and the present day, when it has become a martial art practised throughout the world, is Gichin Funakoshi, the "Father of Karate-do."

Tracy WarrenerGoju Ryu Karate Do Kyohan - by Gogen Yamaguchi 
Full of rare photos of Yamaguchi himself doing katas as well as showing exercises, postures and throws. Hundreds of fine detail line drawings depicting the katas as well as complete analysis of each kata by the founder make this an invaluable asset in the learning of this style.

* COMMENT Making README.md

C-c C-c: Evaluate src block.

#+NAME: make-readme
#+BEGIN_SRC emacs-lisp :results none
(with-temp-buffer
    (insert 
    "#+EXPORT_FILE_NAME: README.md
     #+HTML: <h1> CheatSheet </h1>
     #+OPTIONS: toc:nil d:nil
     # Toc is displayed below at a strategic position.

     This project is to contain a listing of termiology and basics
     for Goju Ryu karate.
     
     *The listing sheet, as PDF, can be found
     [here]({{{URL}}}/blob/master/CheatSheet.pdf)*, 
     while below is an unruly html rendition.
 
     This reference sheet is built around the system
     https://github.com/alhassy/CheatSheet.

     #+TOC: headlines 2
     #+INCLUDE: CheatSheet.org     
    ")
    ;; (set-visited-file-name "ReadIt2.md")
    (org-mode)
    (org-md-export-to-markdown)
)
#+END_SRC

* COMMENT footer

# Local Variables:
# eval: (org-babel-tangle)
# eval: (progn (org-babel-goto-named-src-block "make-readme") (org-babel-execute-src-block) (outline-hide-sublevels 1))
# eval: (load-file "CheatSheet.el")
# compile-command: (my/org-latex-export-to-pdf)
# End:
